"""empty message

Revision ID: 6fb9d14ba3b9
Revises: 8019f7d9aa37
Create Date: 2021-01-10 22:28:47.977941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fb9d14ba3b9'
down_revision = '8019f7d9aa37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('movie_overview', sa.String(length=1000), nullable=True))
    op.add_column('activity', sa.Column('tvshow_overview', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'tvshow_overview')
    op.drop_column('activity', 'movie_overview')
    # ### end Alembic commands ###
